# Generated by Django 2.2.6 on 2019-10-12 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=64)),
                ('user_phone', models.CharField(max_length=16)),
                ('user_password', models.CharField(max_length=16)),
                ('user_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('user_exist', models.BooleanField(default=True)),
            ],
        ),
    ]
