# Generated by Django 2.2.6 on 2019-10-12 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=16)),
                ('product_label', models.CharField(max_length=16)),
                ('product_type', models.CharField(max_length=16)),
                ('product_description', models.CharField(max_length=16)),
                ('product_price', models.CharField(max_length=16)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_offer', models.CharField(max_length=16)),
                ('product_added', models.DateTimeField(default=datetime.datetime.now)),
                ('product_exist', models.BooleanField(default=True)),
            ],
        ),
    ]
